workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 120
    scripts:
      - name: Start Android emulator
        script: emulator -avd emulator > /dev/null 2>&1 &
      - name: Run tests
        script: ./gradlew test
      - name: Build integrated test
        script: ./gradlew assembleAndroidTest