workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 120
    environment:
        java: 17
        groups:
          - codecov_credentials 
    scripts:
      - name: Start Android Emulator
        script: emulator -avd emulator > /dev/null 2>&1 &
      - name: Set Gradle Permissions
        script: chmod +x ./gradlew
      - name: Running Unit Tests
        script: ./gradlew test
      - name: Running Integrated Tests
        script: ./gradlew assembleAndroidTest
      - name: Download Codecov Bash Uploader
        script: curl -O https://codecov.io/bash
      - name: Make Codecov Bash Uploader executable
        script: chmod +x bash
      - name: Generate Test Coverage Report
        script: ./gradlew createDebugCoverageReport
      - name: Upload coverage report to Codecov
        script: ./bash -f  ./app/build/reports/coverage/androidTest/debug/connected/report.xml
